org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.228
loader_version_range=[1,)

mod_license=All Rights Reserved
noreteams_license=GNU Lesser General Public License version 3 (LGPLv3)
norequest_license=MIT
norestages_license=GNU Lesser General Public License version 3 (LGPLv3)
norestagesrdicompat_license=MIT
mod_version=0.1.0
noreteams_version=0.1.1
norequest_version=0.1.1
norestages_version=0.1.1
norestages_rdi_compat_version=0.1.0
mod_group_id=com.nore
